services:
  elasticsearch:
    container_name: station-elasticsearch
    restart: on-failure
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    container_name: station-kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch

volumes:
  elastic-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: data/elastic-data
