service: newsapi-crawl
app: newsapi-crawl-app
org: louisguitton93

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    # https://www.serverless.com/blog/serverless-secrets-api-keys
    NEWSAPI_KEY: ${param:newsapiKey}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: arn:aws:s3:::articles-louisguitton/*

functions:
  newsapi-run:
    handler: handler.run
    events:
      # hourly at 5 past
      # https://www.serverless.com/framework/docs/providers/aws/events/schedule/
      - schedule: cron(5 0 * * ? *)

plugins:
  - serverless-python-requirements
